### ISSUE TITLE
Bug: Drift Leggings Texture Error when paired with Optifine

### ISSUE THREAD

**Issue by Bluyidark** [lunarbunten/enderscape#24]
Drift leggings will show error texture when the mod is used together with optifine. Without optifine it will just be doing fine. Is it possible to have this bug fixed so the mod is compatible with optifine? Thanks for your work! 

![2022-12-06_02 13 45](https://user-images.githubusercontent.com/112769984/205711615-3f799473-823e-4105-a48e-369a275a47dd.png)

**Comment by lunarbunten** [comment]
dont use optifine
